import * as THREE from 'three'
import { hex2rgb } from './utils'

const rgb2three = (c) => {
  return new THREE.Vector3(c.r / 255., c.g / 255., c.b / 255.)
}

export const gradients = {
  tours: {
    u_point1 : { type : "v2", value : new THREE.Vector2(0.8, 0.0) },
    u_color1 : { type: "v3", value: rgb2three(hex2rgb('#F99B82')) },
    u_radius1: { type: "f", value: 10 },
    u_point2 : { type : "v2", value : new THREE.Vector2(0., 0.1) },
    u_color2 : { type: "v3", value: rgb2three(hex2rgb('#93E5F9')) },
    u_radius2: { type: "f", value: 10 },
    u_point3 : { type : "v2", value : new THREE.Vector2(0.93, 0.55) },
    u_color3 : { type: "v3", value: rgb2three(hex2rgb('#00A4ED')) },
    u_radius3: { type: "f", value: 10 },
    u_point4 : { type : "v2", value : new THREE.Vector2(-0.05, 0.85) },
    u_color4 : { type: "v3", value: rgb2three(hex2rgb('#E64FEB')) },
    u_radius4: { type: "f", value: 10 },
    u_point5 : { type : "v2", value : new THREE.Vector2(0.6, 0.95) },
    u_color5 : { type: "v3", value: rgb2three(hex2rgb('#93E5F9')) },
    u_radius5: { type: "f", value: 10 },
  },
  about: {
    u_point1 : { type : "v2", value : new THREE.Vector2(0.05, 0.55) },
    u_color1 : { type: "v3", value: rgb2three(hex2rgb('#0F0C7A')) },
    u_radius1: { type: "f", value: 50 },
    u_point2 : { type : "v2", value : new THREE.Vector2(0.3, 0.9) },
    u_color2 : { type: "v3", value: rgb2three(hex2rgb('#FF83C3')) },
    u_radius2: { type: "f", value: 10 },
    u_point3 : { type : "v2", value : new THREE.Vector2(0.93, 0.05) },
    u_color3 : { type: "v3", value: rgb2three(hex2rgb('#ED0072')) },
    u_radius3: { type: "f", value: 10 },
    u_point4 : { type : "v2", value : new THREE.Vector2(0.7, 0.6) },
    u_color4 : { type: "v3", value: rgb2three(hex2rgb('#FFB31A')) },
    u_radius4: { type: "f", value: 300 },
    u_point5 : { type : "v2", value : new THREE.Vector2(1.1, 0.9) },
    u_color5 : { type: "v3", value: rgb2three(hex2rgb('#FFB31A')) },
    u_radius5: { type: "f", value: 1 },
  },
  book: {
    u_point1 : { type : "v2", value : new THREE.Vector2(0.65, 0.15) },
    u_color1 : { type: "v3", value: rgb2three(hex2rgb('#F6AB3B')) },
    u_radius1: { type: "f", value: -100 },
    u_point2 : { type : "v2", value : new THREE.Vector2(0.8, 0.9) },
    u_color2 : { type: "v3", value: rgb2three(hex2rgb('#60D9B7')) },
    u_radius2: { type: "f", value: 10 },
    u_point3 : { type : "v2", value : new THREE.Vector2(0.9, 0.4) },
    u_color3 : { type: "v3", value: rgb2three(hex2rgb('#9CD9EC')) },
    u_radius3: { type: "f", value: 1 },
    u_point4 : { type : "v2", value : new THREE.Vector2(0.1, 0.9) },
    u_color4 : { type: "v3", value: rgb2three(hex2rgb('#00ACE8')) },
    u_radius4: { type: "f", value: 1 },
    u_point5 : { type : "v2", value : new THREE.Vector2(0.1, -0.4) },
    u_color5 : { type: "v3", value: rgb2three(hex2rgb('#60D9B7')) },
    u_radius5: { type: "f", value: 1 },
  },
  watch: {
    u_point1 : { type : "v2", value : new THREE.Vector2(0.15, 0.85) },
    u_color1 : { type: "v3", value: rgb2three(hex2rgb('#FFB71C')) },
    u_radius1: { type: "f", value: 100 },
    u_point2 : { type : "v2", value : new THREE.Vector2(0.9, -0.1) },
    u_color2 : { type: "v3", value: rgb2three(hex2rgb('#D9E205')) },
    u_radius2: { type: "f", value: -200 },
    u_point3 : { type : "v2", value : new THREE.Vector2(0.9, 0.8) },
    u_color3 : { type: "v3", value: rgb2three(hex2rgb('#9BD8EB')) },
    u_radius3: { type: "f", value: 1 },
    u_point4 : { type : "v2", value : new THREE.Vector2(0.1, 0.1) },
    u_color4 : { type: "v3", value: rgb2three(hex2rgb('#B9DAB1')) },
    u_radius4: { type: "f", value: 100 },
    u_point5 : { type : "v2", value : new THREE.Vector2(-0.4, -0.4) },
    u_color5 : { type: "v3", value: rgb2three(hex2rgb('#B9DAB1')) },
    u_radius5: { type: "f", value: -100 },
  },
  faq: {
    u_point1 : { type : "v2", value : new THREE.Vector2(0.15, 0.85) },
    u_color1 : { type: "v3", value: rgb2three(hex2rgb('#A59AFF')) },
    u_radius1: { type: "f", value: 100 },
    u_point2 : { type : "v2", value : new THREE.Vector2(0.85, 0.1) },
    u_color2 : { type: "v3", value: rgb2three(hex2rgb('#5EEE9E')) },
    u_radius2: { type: "f", value: 50 },
    u_point3 : { type : "v2", value : new THREE.Vector2(0.9, 0.8) },
    u_color3 : { type: "v3", value: rgb2three(hex2rgb('#5257CF')) },
    u_radius3: { type: "f", value: 1 },
    u_point4 : { type : "v2", value : new THREE.Vector2(0.1, 0.1) },
    u_color4 : { type: "v3", value: rgb2three(hex2rgb('#FFAA84')) },
    u_radius4: { type: "f", value: -100 },
    u_point5 : { type : "v2", value : new THREE.Vector2(-0.4, -0.4) },
    u_color5 : { type: "v3", value: rgb2three(hex2rgb('#FFAA84')) },
    u_radius5: { type: "f", value: -100 },
  },
}